matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: "WebPack & Build"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode9.3
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script: cd demo-ng && npm run build.plugin && npm i && tns build ios --bundle --env.uglify --env.aot
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 8
      script: cd demo-ng && npm run build.plugin && npm i && tns build android --bundle --env.uglify --env.aot
    - language: android
      env:
        - BuildAndroid="27"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build android --bundle --env.uglify
    - os: osx
      env:
        - BuildiOS="11"
        - Xcode="9.3"
      osx_image: xcode9.3
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd src && npm i && npm run tsc && cd ../demo && tns build ios --bundle --env.uglify

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - android-26
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
